/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 * @author Adrian, Giangranco y Alirio
 */
public class Interfaz extends javax.swing.JFrame {

    // 1. ATRIBUTOS (En la zona blanca inicial)
    private final Controlador ctrl = new Controlador();
    private final DefaultListModel<String> modeloListaUsuarios = new DefaultListModel<>();
    private final DefaultListModel<String> modeloListaDocs = new DefaultListModel<>();

    public Interfaz() {
        initComponents();
        jList1.setModel(modeloListaUsuarios);
        jList2.setModel(modeloListaDocs);
        
        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                actualizarListaDocs();
            }
        });
        
        if (jLabel4 != null) jLabel4.setText("Reloj: 0.0 Seg");
    }

    // --- MÉTODOS DE SOPORTE (Fuera de cualquier otro método) ---

    private void actualizarListaUsuarios() { // <--- AQUÍ YA NO DARÁ ERROR
        modeloListaUsuarios.clear();
        if (ctrl.usuarios != null) {
            for (Modelo.Usuario u : ctrl.usuarios) {
                modeloListaUsuarios.addElement(u.nombre);
            }
        }
    }

    private void actualizarListaDocs() {
        modeloListaDocs.clear();
        String seleccionado = jList1.getSelectedValue();
        if (seleccionado != null) {
            for (Modelo.Usuario u : ctrl.usuarios) {
                if (u.nombre.equals(seleccionado)) {
                    for (Modelo.Documento d : u.documentos) {
                        String estado = d.enCola ? " [EN COLA]" : "";
                        modeloListaDocs.addElement(d.nombre + estado);
                    }
                    break;
                }
            }
        }
    }

    private void actualizarTodo() {
        // Usamos jTable2 que es la que se ve en tu diseño
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); 

        if (ctrl.cola != null) {
            for (Estructura.Monticulo.Nodo n : ctrl.cola.getElementos()) {
                model.addRow(new Object[]{
                    n.doc.id, 
                    n.doc.nombre, 
                    String.format("%.2f", n.etiqueta), 
                    n.doc.dueño.nombre
                });
            }
        }
        
        jLabel4.setText("Reloj: " + String.format("%.1f", ctrl.reloj) + " Seg");
        jPanel5.repaint(); 
        actualizarListaDocs();
    }

    // --- DIBUJO DEL ÁRBOL ---
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (jPanel5 != null && ctrl != null) {
            dibujarArbol(jPanel5.getGraphics());
        }
    }

    private void dibujarArbol(Graphics g) {
        if (g == null) return;
        List<Estructura.Monticulo.Nodo> nodos = ctrl.cola.getElementos();
        if (nodos.isEmpty()) return;
        dibujarNodo(g, 0, jPanel5.getWidth() / 2, 30, jPanel5.getWidth() / 4, nodos);
    }

    private void dibujarNodo(Graphics g, int i, int x, int y, int off, List<Estructura.Monticulo.Nodo> lista) {
        if (i < lista.size()) {
            g.setColor(Color.BLACK);
            if (2 * i + 1 < lista.size()) g.drawLine(x, y, x - off, y + 50);
            if (2 * i + 2 < lista.size()) g.drawLine(x, y, x + off, y + 50);
            g.setColor(new Color(173, 216, 230));
            g.fillOval(x - 15, y - 15, 30, 30);
            g.setColor(Color.BLACK);
            g.drawOval(x - 15, y - 15, 30, 30);
            g.drawString(String.valueOf(i), x - 5, y + 5);
            dibujarNodo(g, 2 * i + 1, x - off, y + 50, off / 2, lista);
            dibujarNodo(g, 2 * i + 2, x + off, y + 50, off / 2, lista);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BtnCargarCSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        BtnUsuarioManual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        BtnCrearDoc = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btnprioritario = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        BtnCargarCSV.setText("Cargar usuario (CSV)");
        BtnCargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarCSVActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Usuario / Prioridad");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTA", "MEDIA", "BAJA" }));

        BtnUsuarioManual.setText("Agregar usuario manual");
        BtnUsuarioManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioManualActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel2.setText("Documentos por usuario");

        BtnCrearDoc.setText("Crear Doc");
        BtnCrearDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearDocActionPerformed(evt);
            }
        });

        btnimprimir.setText("Mandar a imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnprioritario.setText("¿Es prioritario?");
        btnprioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprioritarioActionPerformed(evt);
            }
        });

        jButton1.setText("Liberar impresora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Doc a eliminar:");

        jButton2.setText("Eliminar de la cola");

        jLabel3.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        jLabel3.setText("Alirio, Adrian, Gianfranco");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnUsuarioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCrearDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprioritario, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(24, 24, 24)
                                    .addComponent(jButton2))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BtnCargarCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnUsuarioManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCrearDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprioritario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Prioridad", "usuario"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarCSVActionPerformed
        ctrl.cargarUsuariosCSV();
        actualizarListaUsuarios();
    }//GEN-LAST:event_BtnCargarCSVActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnprioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprioritarioActionPerformed
    Estructura.Monticulo.Nodo impreso = ctrl.cola.eliminarMin();
    if (impreso != null) {
        impreso.doc.enCola = false;
        ctrl.tabla.eliminar(impreso.doc.id);
        actualizarTodo();
        JOptionPane.showMessageDialog(this, "Se ha impreso: " + impreso.doc.nombre);
    } else {
        JOptionPane.showMessageDialog(this, "La cola está vacía");
    }
    }//GEN-LAST:event_btnprioritarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Estructura.Monticulo.Nodo n = ctrl.cola.eliminarMin();
        if (n != null) {
            n.doc.enCola = false;
            ctrl.tabla.eliminar(n.doc.id);
            actualizarTodo();
        }
    }                                        

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnCrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearDocActionPerformed
    String userNom = jList1.getSelectedValue();
        if (userNom == null) return;
        String nombreDoc = JOptionPane.showInputDialog(this, "Nombre del documento:");
        String paginas = JOptionPane.showInputDialog(this, "Páginas:");
        if (nombreDoc != null && paginas != null) {
            try {
                for (Modelo.Usuario u : ctrl.usuarios) {
                    if (u.nombre.equals(userNom)) {
                        u.documentos.add(new Modelo.Documento(nombreDoc, Integer.parseInt(paginas), "PDF", u));
                        break;
                    }
                }
                actualizarListaDocs();
            } catch (Exception e) { }
        }    }//GEN-LAST:event_BtnCrearDocActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
    String docNom = jList2.getSelectedValue();
        String userNom = jList1.getSelectedValue();
        if (docNom != null && userNom != null) {
            String nombreLimpio = docNom.replace(" [EN COLA]", "");
            for (Modelo.Usuario u : ctrl.usuarios) {
                if (u.nombre.equals(userNom)) {
                    for (Modelo.Documento d : u.documentos) {
                        if (d.nombre.equals(nombreLimpio) && !d.enCola) {
                            ctrl.enviarAImprimir(d, btnprioritario.isSelected());
                            actualizarTodo();
                            return;
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void BtnUsuarioManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioManualActionPerformed
String nombre = jTextField1.getText().trim();
    Object seleccionado = jComboBox1.getSelectedItem(); 

    if (nombre.isEmpty() || seleccionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese nombre y seleccione prioridad.");
        return;
    }

    try {
        // Limpiamos el texto: quitamos espacios y pasamos a MAYÚSCULAS
        String prioridadTexto = seleccionado.toString().trim().toUpperCase();
        
        // Buscamos la constante en el Enum de Modelo
        Modelo.TipoPrioridad tp = Modelo.TipoPrioridad.valueOf(prioridadTexto);
        
        // Agregamos el usuario al controlador
        ctrl.usuarios.add(new Modelo.Usuario(nombre, tp));
        
        // Refrescamos la lista visual
        actualizarListaUsuarios();
        
        // Limpiamos el campo de texto para el próximo usuario
        jTextField1.setText("");
        
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Error: La opción '" + seleccionado + "' no es válida.\n"
                + "Asegúrese de que el ComboBox solo tenga: ALTA, MEDIA o BAJA.");
    }    }//GEN-LAST:event_BtnUsuarioManualActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargarCSV;
    private javax.swing.JButton BtnCrearDoc;
    private javax.swing.JButton BtnUsuarioManual;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JToggleButton btnprioritario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
// === MÉTODOS DE SOPORTE (PEGA ESTO EN ZONA BLANCA AL FINAL) ===

